// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/rpc_meta.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2frpc_5fmeta_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2frpc_5fmeta_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2frpc_5fmeta_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2frpc_5fmeta_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2frpc_5fmeta_2eproto;
namespace mprpc {
class MprpcRequestMeta;
struct MprpcRequestMetaDefaultTypeInternal;
extern MprpcRequestMetaDefaultTypeInternal _MprpcRequestMeta_default_instance_;
class MprpcResponseMeta;
struct MprpcResponseMetaDefaultTypeInternal;
extern MprpcResponseMetaDefaultTypeInternal _MprpcResponseMeta_default_instance_;
}  // namespace mprpc
PROTOBUF_NAMESPACE_OPEN
template<> ::mprpc::MprpcRequestMeta* Arena::CreateMaybeMessage<::mprpc::MprpcRequestMeta>(Arena*);
template<> ::mprpc::MprpcResponseMeta* Arena::CreateMaybeMessage<::mprpc::MprpcResponseMeta>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mprpc {

// ===================================================================

class MprpcRequestMeta final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mprpc.MprpcRequestMeta) */ {
 public:
  inline MprpcRequestMeta() : MprpcRequestMeta(nullptr) {}
  ~MprpcRequestMeta() override;
  explicit PROTOBUF_CONSTEXPR MprpcRequestMeta(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MprpcRequestMeta(const MprpcRequestMeta& from);
  MprpcRequestMeta(MprpcRequestMeta&& from) noexcept
    : MprpcRequestMeta() {
    *this = ::std::move(from);
  }

  inline MprpcRequestMeta& operator=(const MprpcRequestMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline MprpcRequestMeta& operator=(MprpcRequestMeta&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MprpcRequestMeta& default_instance() {
    return *internal_default_instance();
  }
  static inline const MprpcRequestMeta* internal_default_instance() {
    return reinterpret_cast<const MprpcRequestMeta*>(
               &_MprpcRequestMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MprpcRequestMeta& a, MprpcRequestMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(MprpcRequestMeta* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MprpcRequestMeta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MprpcRequestMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MprpcRequestMeta>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MprpcRequestMeta& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MprpcRequestMeta& from) {
    MprpcRequestMeta::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MprpcRequestMeta* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mprpc.MprpcRequestMeta";
  }
  protected:
  explicit MprpcRequestMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceNameFieldNumber = 1,
    kMethodNameFieldNumber = 2,
    kTimeoutMsFieldNumber = 3,
  };
  // string service_name = 1;
  void clear_service_name();
  const std::string& service_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_service_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_service_name();
  PROTOBUF_NODISCARD std::string* release_service_name();
  void set_allocated_service_name(std::string* service_name);
  private:
  const std::string& _internal_service_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_service_name(const std::string& value);
  std::string* _internal_mutable_service_name();
  public:

  // string method_name = 2;
  void clear_method_name();
  const std::string& method_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_method_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_method_name();
  PROTOBUF_NODISCARD std::string* release_method_name();
  void set_allocated_method_name(std::string* method_name);
  private:
  const std::string& _internal_method_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_method_name(const std::string& value);
  std::string* _internal_mutable_method_name();
  public:

  // uint32 timeout_ms = 3;
  void clear_timeout_ms();
  uint32_t timeout_ms() const;
  void set_timeout_ms(uint32_t value);
  private:
  uint32_t _internal_timeout_ms() const;
  void _internal_set_timeout_ms(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:mprpc.MprpcRequestMeta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_name_;
    uint32_t timeout_ms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frpc_5fmeta_2eproto;
};
// -------------------------------------------------------------------

class MprpcResponseMeta final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mprpc.MprpcResponseMeta) */ {
 public:
  inline MprpcResponseMeta() : MprpcResponseMeta(nullptr) {}
  ~MprpcResponseMeta() override;
  explicit PROTOBUF_CONSTEXPR MprpcResponseMeta(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MprpcResponseMeta(const MprpcResponseMeta& from);
  MprpcResponseMeta(MprpcResponseMeta&& from) noexcept
    : MprpcResponseMeta() {
    *this = ::std::move(from);
  }

  inline MprpcResponseMeta& operator=(const MprpcResponseMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline MprpcResponseMeta& operator=(MprpcResponseMeta&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MprpcResponseMeta& default_instance() {
    return *internal_default_instance();
  }
  static inline const MprpcResponseMeta* internal_default_instance() {
    return reinterpret_cast<const MprpcResponseMeta*>(
               &_MprpcResponseMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MprpcResponseMeta& a, MprpcResponseMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(MprpcResponseMeta* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MprpcResponseMeta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MprpcResponseMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MprpcResponseMeta>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MprpcResponseMeta& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MprpcResponseMeta& from) {
    MprpcResponseMeta::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MprpcResponseMeta* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mprpc.MprpcResponseMeta";
  }
  protected:
  explicit MprpcResponseMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMsgFieldNumber = 1,
  };
  // string error_msg = 1;
  void clear_error_msg();
  const std::string& error_msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_msg();
  PROTOBUF_NODISCARD std::string* release_error_msg();
  void set_allocated_error_msg(std::string* error_msg);
  private:
  const std::string& _internal_error_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_msg(const std::string& value);
  std::string* _internal_mutable_error_msg();
  public:

  // @@protoc_insertion_point(class_scope:mprpc.MprpcResponseMeta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_msg_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frpc_5fmeta_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MprpcRequestMeta

// string service_name = 1;
inline void MprpcRequestMeta::clear_service_name() {
  _impl_.service_name_.ClearToEmpty();
}
inline const std::string& MprpcRequestMeta::service_name() const {
  // @@protoc_insertion_point(field_get:mprpc.MprpcRequestMeta.service_name)
  return _internal_service_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MprpcRequestMeta::set_service_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.service_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mprpc.MprpcRequestMeta.service_name)
}
inline std::string* MprpcRequestMeta::mutable_service_name() {
  std::string* _s = _internal_mutable_service_name();
  // @@protoc_insertion_point(field_mutable:mprpc.MprpcRequestMeta.service_name)
  return _s;
}
inline const std::string& MprpcRequestMeta::_internal_service_name() const {
  return _impl_.service_name_.Get();
}
inline void MprpcRequestMeta::_internal_set_service_name(const std::string& value) {
  
  _impl_.service_name_.Set(value, GetArenaForAllocation());
}
inline std::string* MprpcRequestMeta::_internal_mutable_service_name() {
  
  return _impl_.service_name_.Mutable(GetArenaForAllocation());
}
inline std::string* MprpcRequestMeta::release_service_name() {
  // @@protoc_insertion_point(field_release:mprpc.MprpcRequestMeta.service_name)
  return _impl_.service_name_.Release();
}
inline void MprpcRequestMeta::set_allocated_service_name(std::string* service_name) {
  if (service_name != nullptr) {
    
  } else {
    
  }
  _impl_.service_name_.SetAllocated(service_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.service_name_.IsDefault()) {
    _impl_.service_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mprpc.MprpcRequestMeta.service_name)
}

// string method_name = 2;
inline void MprpcRequestMeta::clear_method_name() {
  _impl_.method_name_.ClearToEmpty();
}
inline const std::string& MprpcRequestMeta::method_name() const {
  // @@protoc_insertion_point(field_get:mprpc.MprpcRequestMeta.method_name)
  return _internal_method_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MprpcRequestMeta::set_method_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.method_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mprpc.MprpcRequestMeta.method_name)
}
inline std::string* MprpcRequestMeta::mutable_method_name() {
  std::string* _s = _internal_mutable_method_name();
  // @@protoc_insertion_point(field_mutable:mprpc.MprpcRequestMeta.method_name)
  return _s;
}
inline const std::string& MprpcRequestMeta::_internal_method_name() const {
  return _impl_.method_name_.Get();
}
inline void MprpcRequestMeta::_internal_set_method_name(const std::string& value) {
  
  _impl_.method_name_.Set(value, GetArenaForAllocation());
}
inline std::string* MprpcRequestMeta::_internal_mutable_method_name() {
  
  return _impl_.method_name_.Mutable(GetArenaForAllocation());
}
inline std::string* MprpcRequestMeta::release_method_name() {
  // @@protoc_insertion_point(field_release:mprpc.MprpcRequestMeta.method_name)
  return _impl_.method_name_.Release();
}
inline void MprpcRequestMeta::set_allocated_method_name(std::string* method_name) {
  if (method_name != nullptr) {
    
  } else {
    
  }
  _impl_.method_name_.SetAllocated(method_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.method_name_.IsDefault()) {
    _impl_.method_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mprpc.MprpcRequestMeta.method_name)
}

// uint32 timeout_ms = 3;
inline void MprpcRequestMeta::clear_timeout_ms() {
  _impl_.timeout_ms_ = 0u;
}
inline uint32_t MprpcRequestMeta::_internal_timeout_ms() const {
  return _impl_.timeout_ms_;
}
inline uint32_t MprpcRequestMeta::timeout_ms() const {
  // @@protoc_insertion_point(field_get:mprpc.MprpcRequestMeta.timeout_ms)
  return _internal_timeout_ms();
}
inline void MprpcRequestMeta::_internal_set_timeout_ms(uint32_t value) {
  
  _impl_.timeout_ms_ = value;
}
inline void MprpcRequestMeta::set_timeout_ms(uint32_t value) {
  _internal_set_timeout_ms(value);
  // @@protoc_insertion_point(field_set:mprpc.MprpcRequestMeta.timeout_ms)
}

// -------------------------------------------------------------------

// MprpcResponseMeta

// string error_msg = 1;
inline void MprpcResponseMeta::clear_error_msg() {
  _impl_.error_msg_.ClearToEmpty();
}
inline const std::string& MprpcResponseMeta::error_msg() const {
  // @@protoc_insertion_point(field_get:mprpc.MprpcResponseMeta.error_msg)
  return _internal_error_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MprpcResponseMeta::set_error_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mprpc.MprpcResponseMeta.error_msg)
}
inline std::string* MprpcResponseMeta::mutable_error_msg() {
  std::string* _s = _internal_mutable_error_msg();
  // @@protoc_insertion_point(field_mutable:mprpc.MprpcResponseMeta.error_msg)
  return _s;
}
inline const std::string& MprpcResponseMeta::_internal_error_msg() const {
  return _impl_.error_msg_.Get();
}
inline void MprpcResponseMeta::_internal_set_error_msg(const std::string& value) {
  
  _impl_.error_msg_.Set(value, GetArenaForAllocation());
}
inline std::string* MprpcResponseMeta::_internal_mutable_error_msg() {
  
  return _impl_.error_msg_.Mutable(GetArenaForAllocation());
}
inline std::string* MprpcResponseMeta::release_error_msg() {
  // @@protoc_insertion_point(field_release:mprpc.MprpcResponseMeta.error_msg)
  return _impl_.error_msg_.Release();
}
inline void MprpcResponseMeta::set_allocated_error_msg(std::string* error_msg) {
  if (error_msg != nullptr) {
    
  } else {
    
  }
  _impl_.error_msg_.SetAllocated(error_msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_msg_.IsDefault()) {
    _impl_.error_msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mprpc.MprpcResponseMeta.error_msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mprpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2frpc_5fmeta_2eproto
